name: boostdrive_workspace
description: A monorepo for the BoostDrive Ecosystem.
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  melos: ^3.0.0












































































































